# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ff7246390204df1f30400cfc8ef9d608b754b7b3cbd22fc8dce59525c5a98b0dbd87b5377666401123351ce2b5f91bd5807a221ea46ec1a139425bc76804bf

test:
  secret_key_base: b687b01a8857ce705448fa36604818034f0fd3fd4337ce9bc04699df3627a3928cf6ffd9041f01e37e8e295652b6a9319f342d47bbf9b90aae09ecaf28c8b736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
